language: android

before_install:
  - wget http://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip
  - unzip -q android-ndk-r18b-linux-x86_64.zip -d /usr/local/android-sdk
  - mv /usr/local/android-sdk/android-ndk-r18b /usr/local/android-sdk/ndk-bundle

android:
  components:

    # We call "tools" twice to get the latest Android SDK tools.
    - tools
    - platform-tools
    - tools

    # The SDK version used to compile this program. This is NOT the minimum requirement.
    - android-27

    # We need a specific version of BuildTools to get this working.
    - build-tools-28.0.3
